### ISSUE TITLE
Ollama is running in background in MacOS

### ISSUE THREAD

**Issue by MagzhanUnited** [jmorganca/ollama#1925]
Even if I exit the ollama app I can see the ollama among run processes

**Comment by jmorganca** [comment]
Hi @MagzhanUnited, sorry, that definitely shouldn't be the case. Will look into this

**Comment by MagzhanUnited** [comment]
> Hi @MagzhanUnited, sorry, that definitely shouldn't be the case. Will look into this

Thanks. I also couldn't kill process. Ollama always recreates a new process

**Comment by maderix** [comment]
for ubuntu atleast the way to stop ollama serve is "sudo systemctl stop ollama.service"

**Comment by dhiltgen** [comment]
@MagzhanUnited the behavior you describe makes it sound like the App is still running.  Is it possible it's "hidden" by the camera notch on your laptop due to lots of other tray apps running?   The CLI will auto-start the App on MacOS if it's not running, and the App in turn will start the server.

**Comment by rovo79** [comment]
I have not started Ollama in a while, and I don't have running but I still continue to see an Ollama process in the background:
<img width="734" alt="image" src="https://github.com/ollama/ollama/assets/117691/249e68cf-6488-4ed6-8aa9-190fa56b36a5">

**Comment by dhiltgen** [comment]
@rovo79 ollama is a client-server application, with a GUI component on MacOS.  The server process is managed by the tray (menu bar) app.  When you quit the app from the pull-down menu, it should stop the server process running in the background.  If you try to run the CLI later, it detects the app isn't running, and will start it, which in turn starts the server.

**Comment by psylone** [comment]
Also Ollama could be in the System Settings -> General -> Login Items: Open at Login section on macOS. It means that after restart Ollama app will start automatically.

**Comment by markus-seidl** [comment]
Every time I remove OLlama from the login items, it re-adds itself again. That's very annoying.

**Comment by jmorganca** [comment]
@markus-seidl that's definitely a bug – will look into this

**Comment by oricoh** [comment]
Any update on this? It still keeps re-adding itself to the login items

**Comment by unobatbayar** [comment]
Why does Ollama need to be running at all if we're running installed models?

**Comment by dhiltgen** [comment]
This should be resolved in the latest version of the mac app.  If you disable login support, it shouldn't reset it back now.

**Comment by j05hau** [comment]
This is still a problem with the latest dmg. 

I don't see the app in Open at Login settings

I can't uninstall, even with:

```sudo rm -rf /Applications/Ollama.app
sudo rm /usr/local/bin/ollama
rm -rf "~/Library/Application Support/Ollama"
rm -rf "~/Library/Saved Application State/com.electron.ollama.savedState"
rm -rf ~/Library/Caches/com.electron.ollama/
rm -rf ~/Library/Caches/ollama
rm -rf ~/Library/WebKit/com.electron.ollama
rm -rf ~/.ollama
```
However it does show itself in the Allow in Background section

Moving the app to the bin from Applications doesn't delete it as it starts back up the next time macOS boots and asks to move Ollama to the Applications folder and to install the CLI. So something uninstalls but something clearly remains. The app must be in some temp folder and attempts to reinstall itself from some sort of linkage. 

Pretty annoying, I am going to have to reset the mac over this.

**Comment by j05hau** [comment]
Figured it out - the deleted .app **that was in the trash can** resurrected itself after every reboot of macOS. That's a malware-tier bug. This ain't fixed!

```
source=app_darwin.go:215 msg="starting Ollama" app="/Users/username/.Trash/Ollama 6.14.32\u202fpm.app" version=0.9.6 OS=Darwin/24.5.0
```

**Comment by unobatbayar** [comment]
Almost as if it's done by design.

**Comment by jmorganca** [comment]
@j05hau sorry you hit this. I can't reproduce this on the newest version of macOS (15.5) but will investigate older versions which may have this issue. Which version of macOS are you on?

**Comment by j05hau** [comment]
> [@j05hau](https://github.com/j05hau) sorry you hit this. I can't reproduce this on the newest version of macOS (15.5) but will investigate older versions which may have this issue. Which version of macOS are you on?

Sorry for the delayed response, @jmorganca. I'm on the latest version, 15.6. I can't really give you repro steps unfortunately, because it just happened from the basic installation process. I'm having a couple problems with the app, it won't auto-update either, just sits there with 'restart to update' and when i click it nothing happens. Must have got a dud.

I believe that macOS doesn't have a check for apps in the trash and will just run them if they are called, pretty insane.

**Comment by Kyvrel** [comment]
+1, I deleted the "open at login" items, but it still starts up when I boot up.

**Comment by ChristopherSchultz** [comment]
I was a bit confused by the behavior as well. When run run the Ollama application, it also runs what looks like a helper application which appears in the menu bar extras (over by the WiFi and stuff). When you quit the main application, that helper app continues to run. If you quit both the main application *and then* quit the helper application, the background web server process does stop.

I'm not happy with how this worked and I was ready to scorch the earth. I may still do so, because this is really not an okay for an application to behave.

**Comment by Qhilm** [comment]
Same here on macOS 26.4.1. Opening ollama.app or running "ollama" in the terminal will launch a bunch of ollama processes which are not terminated when exiting. I can exit any process containing "ollama" using the activity monitor,  but that is not really optimal.

**Comment by mertdeveci5** [comment]
This still keeps happening to the extent that I had to uninstall Ollama. 

Kindly prioritise the fix here please. On quit, Ollama should simply quit and not run any processes. It would also be good to have Ollama not add itself as a login item by default. This can be an option in config though
